# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.4
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: python -m pip install --user --upgrade pip pipenv

      - run:
          name: lock 
          command: pipenv lock --dev
      - run:
          name: requirements 
          command: pipenv lock -r > requirements.txt
      - run:
          name: requirements-dev
          command: pipenv lock -r -d > requirements-dev.txt

      - store_artifacts:
          path: Pipfile.lock
          destination: Pipfile.lock

      - store_artifacts:
          path: requirements.txt
          destination: requirements.txt

      - store_artifacts:
          path: requirements-dev.txt
          destination: requirements-dev.txt
